x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-10m}"
    max-file: "${LOG_MAX_FILE:-3}"
    compress: "${LOG_COMPRESS:-true}"

services:
  unbound:
    container_name: unbound
    image: ${IMAGE:-ghcr.io/zyrakq/unbound:latest}
    restart: unless-stopped
    logging: *default-logging
    environment:
      ACCESS_CONTROL_CUSTOM: ${ACCESS_CONTROL_CUSTOM}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}
      BLOCK_PRIVATE: ${BLOCK_PRIVATE:-false}
      ENABLE_DNSSEC: ${ENABLE_DNSSEC:-true}
      ENABLE_CACHE: ${ENABLE_CACHE:-true}
    networks:
      - unbound-network

networks:
  unbound-network:
    name: unbound-network
